version: '3.7'
services: 
  go-boilerplate-mysql:
    container_name: go-boilerplate-mysql
    image: mysql:8.2
    ports:
      - 3306:3306
    env_file: ../config/mysql/mysql.env
    volumes:
      - ../config/mysql:/docker-entrypoint-initdb.d:ro
      - ../data/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55